[package]
name = "diablo-5"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.3"
glam = { version = "0.20.0", features = ["mint"] }
rand = "0.8.5"
specs = { version = "0.17.0", features = ["specs-derive"] }
